### ISSUE TITLE
SNMP keys don't match config file

### ISSUE THREAD

**Issue by phil-dileo** [arista-eosext/rphm#5]
It looks like there are a few places in the v3 conditional that reference improperly-cased keys.

EG
https://github.com/arista-eosext/rphm/blob/master/rphm/app.py#L857

In short, the keys in the code don't match the keys in the config file.

**Comment by jerearista** [comment]
ConfigParser converts all keys to lower-case.  `rphm --test=parse_only` dumps the parsed configs for confirmation.
